backend:
name: github
repo: zjusticy/blog
branch: main
media_folder: public/img
public_folder: img
base_url: https://blog-six-phi-30.vercel.app
auth_endpoint: api/auth
collections:
  - label: "Blog"
    name: "blog"
    folder: "_data/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
